import { Demora } from "./demora";
import { Firma } from "./firma";
import { Maniobra } from "./maniobra";

export class Servicio {
    codigo: number;
    cliente: number;
    clienteRazonSocial: string;
    fechaPedido: Date;
    buqueNombre: string;
    buqueCoeficiente: number;
    buqueEslora: number;
    buqueManga: number;
    buquePuntal: number;
    buqueSenial: string;
    buqueBandera: string;
    practico1: number;
    practico1Nombre: string;
    practico2: number;
    practico2Nombre: string;
    lugarDesde: string;
    lugarHasta: string;
    lugarKilometros: number;
    fechaInicio: Date;
    fechaFin: string;
    calado_Proa: number;
    calado_Popa: number;
    cabotaje: number;
    observacion: string;
    taraBruta: number;
    taraNeta: number;
    canal: string;
    propietario:string;    
    transfirio?: number;   
    propietarioNombre?: string;
    firmas?:Firma[];
    demorasnuevas?:Demora[];
    maniobrasnuevas?:Maniobra[];
    fechaInicioNavegacion: string;
    fechaABordo: string;
}
