export class Servicio {
    codigo: number;
    cliente: number;
    clienteRazonSocial: string;
    fechaPedido: Date;
    buqueNombre: string;
    buqueCoeficiente: number;
    buqueEslora: number;
    buqueManga: number;
    buquePuntal: number;
    buqueSenial: string;
    buqueBandera: string;
    practico1: number;
    practico1Nombre: string;
    practico2: number;
    practico2Nombre: string;
    lugarDesde: string;
    lugarHasta: string;
    lugarKilometros: number;
    fechaInicio: Date;
    fechaFin: Date;
    calado_Proa: number;
    calado_Popa: number;
    cabotaje: number;
    observacion: string;
    taraBruta: number;
    taraNeta: number;
    canal: string;
}
